# Generated by Django 4.2.10 on 2026-08-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('punto_venta', models.CharField(blank=True, default='', max_length=100)),
                ('salario_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('requisitos', models.TextField(blank=True, default='')),
                ('responsable_hr', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PAUSADA', 'Pausada'), ('CERRADA', 'Cerrada'), ('CUBIERTA', 'Cubierta')], db_index=True, default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('vacantes_disponibles', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacante',
                'db_table': 'vacante',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('etapa', models.CharField(choices=[('POSTULADO', 'Postulado'), ('ENTREVISTA_RH', 'Entrevista RH'), ('ENTREVISTA_JEFE', 'Entrevista Jefe de Área'), ('PRUEBAS', 'Pruebas / Exámenes'), ('OFERTA', 'Oferta enviada'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado'), ('DESISTIO', 'Desistió')], db_index=True, default='POSTULADO', max_length=20)),
                ('fecha_postulacion', models.DateField()),
                ('fuente', models.CharField(blank=True, default='', help_text='Ej: Computrabajo, referido, redes sociales', max_length=100)),
                ('notas', models.TextField(blank=True, default='')),
                ('motivo_rechazo', models.CharField(blank=True, default='', max_length=255)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='reclutamiento.vacante')),
            ],
            options={
                'verbose_name': 'Candidato',
                'db_table': 'candidato',
                'ordering': ['-fecha_postulacion'],
                'indexes': [models.Index(fields=['etapa'], name='candidato_etapa_e9eeee_idx'), models.Index(fields=['cedula'], name='candidato_cedula_2f2c16_idx')],
            },
        ),
    ]
