# Generated by Django 4.2.10 on 2026-08-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0003_colaborador_punto_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_habiles', models.PositiveIntegerField(help_text='Calculado automaticamente: dias de lunes a viernes en el rango')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DISFRUTADA', 'Disfrutada'), ('CANCELADA', 'Cancelada')], db_index=True, default='SOLICITADA', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('aprobado_por', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'db_table': 'solicitud_vacaciones',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['estado'], name='solicitud_v_estado_36993a_idx')],
            },
        ),
    ]
