# Generated by Django 4.2.10 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='origen',
            field=models.CharField(default='MANUAL', help_text='MANUAL o JOTFORM', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='tipo_solicitud',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO_NO_REMUNERADO', 'Permiso no remunerado'), ('PERMISO_REMUNERADO', 'Permiso remunerado'), ('OTRO', 'Otro')], db_index=True, default='VACACIONES', max_length=25),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='responsable_hr',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
