# Generated by Django 4.2.10 on 2026-08-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0004_colaborador_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retiro', models.CharField(choices=[('RENUNCIA_VOLUNTARIA', 'Renuncia voluntaria'), ('DESPIDO_CON_JUSTA_CAUSA', 'Despido con justa causa'), ('DESPIDO_SIN_JUSTA_CAUSA', 'Despido sin justa causa'), ('TERMINACION_CONTRATO', 'Terminación de contrato (vencimiento)'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('ABANDONO_PUESTO', 'Abandono del puesto'), ('OTRO', 'Otro')], default='RENUNCIA_VOLUNTARIA', max_length=25)),
                ('motivo', models.TextField(blank=True, default='')),
                ('fecha_retiro', models.DateField(help_text='Fecha en que se formaliza el retiro')),
                ('ultimo_dia_laborado', models.DateField(blank=True, help_text='Si es distinto a la fecha de retiro (ej. preaviso)', null=True)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('devolucion_dotacion', models.BooleanField(default=False, help_text='Uniforme, herramientas de trabajo')),
                ('devolucion_equipos', models.BooleanField(default=False, help_text='Equipos electrónicos, llaves, accesos')),
                ('paz_y_salvo_emitido', models.BooleanField(default=False)),
                ('carta_laboral_entregada', models.BooleanField(default=False)),
                ('estado_liquidacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('entrevista_realizada', models.BooleanField(default=False)),
                ('entrevista_notas', models.TextField(blank=True, default='')),
                ('recomendable_recontratacion', models.BooleanField(blank=True, help_text='Vacio = no evaluado', null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Retiro',
                'db_table': 'retiro',
                'ordering': ['-fecha_retiro'],
                'indexes': [models.Index(fields=['tipo_retiro'], name='retiro_tipo_re_069978_idx'), models.Index(fields=['estado_liquidacion'], name='retiro_estado__30c988_idx')],
            },
        ),
    ]
