# Generated by Django 4.2.10 on 2026-02-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL')], max_length=3)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('plataforma_url', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'db_table': 'entidad',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arl', models.ForeignKey(blank=True, db_column='id_arl', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_arl', to='colaboradores.entidad')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, to='colaboradores.empresa')),
                ('eps', models.ForeignKey(blank=True, db_column='id_eps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_eps', to='colaboradores.entidad')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'db_table': 'colaborador',
                'ordering': ['nombre'],
            },
        ),
    ]
