# Generated by Django 4.2.10 on 2026-08-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_retiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_bono',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('PROMEDIO', 'Promedio'), ('NINGUNO', 'Sin bono')], default='NINGUNO', max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], default='CC', max_length=3),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='valor_bono',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valor fijo del bono, o promedio histórico si tipo_bono='PROMEDIO'", max_digits=12, null=True),
        ),
    ]
