# Generated by Django 4.2.10 on 2026-08-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='punto_venta',
            field=models.ForeignKey(blank=True, db_column='id_punto_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='puntos_venta.puntoventa'),
        ),
    ]
