# Generated by Django 4.2.10 on 2026-08-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_punto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='caja_compensacion',
            field=models.ForeignKey(blank=True, db_column='id_caja_compensacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_ccf', to='colaboradores.entidad'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fondo_pension',
            field=models.ForeignKey(blank=True, db_column='id_fondo_pension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_afp', to='colaboradores.entidad'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('CCF', 'Caja de Compensación Familiar'), ('AFP', 'Fondo de Pensión')], max_length=3),
        ),
    ]
