# Generated by Django 4.2.10 on 2026-08-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoDisciplinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('punto_venta', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('antiguedad', models.PositiveIntegerField(blank=True, help_text='Antigüedad en años', null=True)),
                ('tipo_proceso', models.CharField(choices=[('LLAMADO_ATENCION', 'Llamado de Atención'), ('CARTA_MEJORA', 'Carta a la Mejora'), ('DESCARGOS', 'Descargos'), ('SUSPENSION', 'Suspensión'), ('COMUNICADO_DISCIPLINARIO', 'Comunicado disciplinario'), ('SIN_ESPECIFICAR', 'Sin especificar'), ('OTRO', 'Otro')], default='SIN_ESPECIFICAR', max_length=30)),
                ('fecha_actuacion', models.DateField()),
                ('motivo', models.TextField()),
                ('responsable_hr', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado'), ('ARCHIVADO', 'Archivado'), ('ABIERTO', 'Abierto'), ('DESISTIDO', 'Desistido')], db_index=True, default='EN_PROCESO', max_length=15)),
                ('resultado', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proceso Disciplinario',
                'db_table': 'proceso_disciplinario',
                'ordering': ['-fecha_actuacion', 'nombre'],
                'indexes': [models.Index(fields=['estado'], name='proceso_dis_estado_f5ac4c_idx'), models.Index(fields=['cedula'], name='proceso_dis_cedula_3f948c_idx')],
            },
        ),
    ]
