# Generated by Django 4.2.10 on 2026-08-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
        ('procesos_disciplinarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesodisciplinario',
            name='colaborador',
            field=models.ForeignKey(blank=True, db_column='id_colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_disciplinarios', to='colaboradores.colaborador'),
        ),
    ]
