# Generated by Django 4.2.10 on 2026-08-28 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id_incapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENFERMEDAD_GENERAL', 'Enfermedad General'), ('ACCIDENTE_LABORAL', 'Accidente Laboral'), ('ENFERMEDAD_LABORAL', 'Enfermedad Laboral'), ('MATERNIDAD', 'Licencia Maternidad'), ('PATERNIDAD', 'Licencia Paternidad')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.IntegerField(default=0)),
                ('diagnostico', models.CharField(blank=True, max_length=300, null=True)),
                ('responsable_pago', models.CharField(choices=[('EMPLEADOR', 'Empleador'), ('EPS', 'EPS'), ('ARL', 'ARL')], default='EPS', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('EN_COBRO', 'En Cobro'), ('PAGADA', 'Pagada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10)),
                ('documento_url', models.CharField(blank=True, max_length=300, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.RESTRICT, related_name='incapacidades', to='colaboradores.colaborador')),
                ('entidad_emisora', models.ForeignKey(blank=True, db_column='id_entidad_emisora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incapacidades', to='colaboradores.entidad')),
                ('incapacidad_padre', models.ForeignKey(blank=True, db_column='id_incapacidad_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prorrogas', to='incapacidades.incapacidad')),
                ('usuario_registro', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.RESTRICT, related_name='incapacidades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'db_table': 'incapacidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
