# Generated by Django 4.2.10 on 2026-08-29 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Término Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZAJE', 'Contrato de Aprendizaje'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], default='FIJO', max_length=25)),
                ('cargo', models.CharField(max_length=100)),
                ('punto_venta', models.CharField(blank=True, default='', max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío para contratos a término indefinido', null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('TERMINADO', 'Terminado'), ('RENOVADO', 'Renovado')], db_index=True, default='VIGENTE', max_length=10)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('motivo_terminacion', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='colaboradores.colaborador')),
                ('contrato_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'db_table': 'contrato',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['estado'], name='contrato_estado_92c569_idx'), models.Index(fields=['fecha_fin'], name='contrato_fecha_f_6733c3_idx')],
            },
        ),
    ]
