# Generated by Django 4.2.10 on 2026-08-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='punto_venta_fk',
            field=models.ForeignKey(blank=True, db_column='id_punto_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='puntos_venta.puntoventa'),
        ),
    ]
