# Generated by Django 4.2.10 on 2026-08-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INDUCCION', 'Inducción'), ('CAPACITACION_TECNICA', 'Capacitación Técnica'), ('SEGURIDAD_SALUD', 'Seguridad y Salud en el Trabajo'), ('LIDERAZGO', 'Liderazgo'), ('SERVICIO_CLIENTE', 'Servicio al Cliente'), ('OTRO', 'Otro')], default='CAPACITACION_TECNICA', max_length=25)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('instructor', models.CharField(blank=True, default='', max_length=150)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_horas', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('punto_venta', models.CharField(blank=True, default='', help_text='Vacío = aplica a todos los puntos', max_length=100)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=10)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacitación',
                'db_table': 'capacitacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asistencia', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('COMPLETADO', 'Completado')], default='INSCRITO', max_length=12)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('certificado_emitido', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='capacitaciones.capacitacion')),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Participante de Capacitación',
                'db_table': 'participante_capacitacion',
                'unique_together': {('capacitacion', 'colaborador')},
            },
        ),
    ]
