# Generated by Django 4.2.10 on 2026-08-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_colaborador_fecha_retiro_colaborador_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: 2026-S1, Q3 2026', max_length=30)),
                ('tipo_evaluacion', models.CharField(choices=[('PERIODO_PRUEBA', 'Periodo de Prueba'), ('JEFE_DIRECTO', 'Evaluación de Jefe Directo'), ('AUTOEVALUACION', 'Autoevaluación'), ('DESEMPENO_360', 'Evaluación 360°')], default='JEFE_DIRECTO', max_length=20)),
                ('fecha_evaluacion', models.DateField()),
                ('evaluador', models.CharField(max_length=150)),
                ('criterios', models.JSONField(default=list)),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fortalezas', models.TextField(blank=True, default='')),
                ('areas_mejora', models.TextField(blank=True, default='')),
                ('plan_accion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADA', 'Completada'), ('ENTREGADA_COLABORADOR', 'Entregada al colaborador')], db_index=True, default='BORRADOR', max_length=25)),
                ('responsable_hr', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'db_table': 'evaluacion_desempeno',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['periodo'], name='evaluacion__periodo_ceece8_idx'), models.Index(fields=['estado'], name='evaluacion__estado_516851_idx')],
            },
        ),
    ]
