# Generated by Django 4.2.10 on 2026-08-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='token_publico',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
