# Generated by Django 4.2.10 on 2026-08-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('colaboradores', '0004_colaborador_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('UNIFORME', 'Uniforme / Dotación'), ('EPP', 'Elemento de Protección Personal')], default='UNIFORME', max_length=10)),
                ('usa_talla', models.BooleanField(default=True, help_text='Si aplica, se controla stock por talla (ropa, botas, etc.)')),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, help_text='Cada cuantos meses se debe reponer (ley/desgaste). Vacío = sin periodicidad fija', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elemento de Dotación/EPP',
                'db_table': 'elemento_dotacion',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('INGRESO', 'Ingreso (dotación inicial)'), ('PERIODICA', 'Entrega periódica (ley)'), ('REPOSICION', 'Reposición por desgaste/daño')], default='INGRESO', max_length=10)),
                ('fecha_entrega', models.DateField()),
                ('responsable_hr', models.CharField(max_length=150)),
                ('firma_recibido', models.BooleanField(default=False, help_text='Constancia de recibido firmada por el colaborador')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='entregas_dotacion', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Entrega de Dotación',
                'db_table': 'entrega_dotacion',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='dotacion.elementodotacion')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dotacion.entregadotacion')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega',
                'db_table': 'detalle_entrega_dotacion',
            },
        ),
        migrations.CreateModel(
            name='RequisitoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Debe coincidir con el cargo del colaborador', max_length=100)),
                ('obligatorio', models.BooleanField(default=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='dotacion.elementodotacion')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_dotacion', to='puntos_venta.puntoventa')),
            ],
            options={
                'verbose_name': 'Requisito de Elemento por Cargo',
                'db_table': 'requisito_elemento',
                'ordering': ['cargo'],
                'unique_together': {('cargo', 'punto_venta', 'elemento')},
            },
        ),
        migrations.CreateModel(
            name='InventarioElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, default='', help_text='Vacío si el elemento no maneja talla', max_length=10)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Debajo de esta cantidad se genera alerta de reposición')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='dotacion.elementodotacion')),
            ],
            options={
                'verbose_name': 'Inventario de Elemento',
                'db_table': 'inventario_elemento',
                'ordering': ['elemento__nombre', 'talla'],
                'unique_together': {('elemento', 'talla')},
            },
        ),
    ]
